### ISSUE TITLE
版本对应问题

### ISSUE THREAD

**Issue by Zhw098** [hannlp/SimpleNMT#1]
您好，非常感谢您分享的机翻新模型，我是想借用机器翻译的模型用于逆合成，但是在训练的时候报错的“ModuleNotFoundError: No module named 'torchtext.legacy'”
我用的版本是：Python=3.7 pytorch=1.6 torchvision=0.7.0 torchtext=0.7.0 cudatoolkit=10.1 
请问您用的版本是什么？
不好意思我看到了，太蠢了，以为torch和pytorch是一样的，抱歉给您添麻烦了

**Comment by Zhw098** [comment]
> 您好，非常感谢您分享的机翻新模型，我是想借用机器翻译的模型用于逆合成，但是在训练的时候报错的“ModuleNotFoundError: No module named 'torchtext.legacy'” 我用的版本是：Python=3.7 pytorch=1.6 torchvision=0.7.0 torchtext=0.7.0 cudatoolkit=10.1 请问您用的版本是什么？

**Comment by hannlp** [comment]
不好意思，没有及时看到，你可能需要把torchtext升级到0.9.0，对应的，pytorch版本也需要升级为1.8.0。如果你无法使用pytorch 1.8.0的话，也可以用torchtext 0.8.1，但是需要把代码中的from torchtext.legacy.** import 中的".legacy"去掉即可，如果有问题欢迎联系我，邮箱是1140325971@qq.com
